[workspace]
members = ["packages/*", "contracts/*"]

# Resolver has to be set explicitely in workspaces, see https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
anybuf = "0.5.0"
anyhow = "1"
bs58 = "0.5.1"
cosmwasm-schema = "2.1.1"
cosmwasm-std = { version="2.1.1" }
cw-controllers = "2.0.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = { version = "2.0.0" }
serde = { version = "1.0.188" }
serde-json-wasm = "1.0.1"
schemars = "0.8.15"
semver = "1"
thiserror = "1.0.4"
cw20-wrapped-2 = { version = "0.1.0", features = ["library"] }
hex = { version = "0.4.3"}
generic-array = { version = "1.1.0" }
k256 = { version = "0.13.3" }
sha3 = { version = "0.10.8" }

[patch.crates-io]
bindings = { path = "packages/bindings", version = "0.1.0" }
cw20-wrapped-2 = { path = "contracts/cw20-wrapped" }
wormhole-cosmwasm = { path = "contracts/wormhole" }

[profile.release.package.sample]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false