---
stages:
  - pre-scans
  - go_lint
  - build_release

include:
  - project: security/security-ci-cd-templates
    file: /qredo-security.gitlab-ci.yml
    ref: master

go_linter:
  stage: go_lint
  image:
    name: 965240221932.dkr.ecr.eu-west-1.amazonaws.com/golang:1.20.4-milagro
    pull_policy: if-not-present
  tags:
    - amd64-eks
    - dev
  rules:
    - if: '$CI_PROJECT_NAME == "fusionchain"'
  script:
    - git config --global url."https://$GITLAB_TOKEN@gitlab.qredo.com".insteadOf "https://gitlab.qredo.com"
    - git config --global url."https://$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
    - bash golint.sh
  allow_failure: true


build and release:
  stage: build_release
  tags:
    - dev
    - amd64-eks
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |-
      /kaniko/executor \
      --context=$CI_PROJECT_NAME \
      --dockerfile=application/Dockerfile \
      --cache=true --cache-ttl=1h \
      --cache-repo=$CI_REGISTRY/$CI_PROJECT_NAME \
      --build-arg GITLAB_TOKEN="$GITLAB_TOKEN" \
      --destination=$CI_REGISTRY/$CI_PROJECT_NAME
  only:
    - tags
