version: 1
build:
  main: cmd/wardend
  binary: wardend
accounts:
- name: alice
  coins:
  - 200000000uward
- name: bob
  coins:
  - 100000000uward
- name: shulgin
  # warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
  mnemonic: exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge
  coins:
  - 200000000uward
client:
  openapi:
    path: docs/static/openapi.yml
  typescript:
    path: "./ts-client"
  hooks:
    path: "./spaceward/src/hooks"
faucet:
  name: bob
  coins:
  - 100000uward
validators:
- name: alice
  bonded: 100000000uward
  home: ~/.warden
genesis:
  app_state:
    warden:
      keychains:
        - id: 1
          is_active: true
          creator: warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
          description: ACME corp
          admins:
            - warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
          parties:
            - warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
          admin_intent_id: 0
          fees:
            key_req: 0
            sig_req: 0
      spaces:
        - id: 1
          creator: warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
          owners:
            - warden10kmgv5gzygnecf46x092ecfe5xcvvv9r870rq4
    staking:
      params:
        bond_denom: "uward"
    gov:
      params:
        min_deposit:
          - denom: "uward"
            amount: "100000"
        expedited_min_deposit:
          - denom: "uward"
            amount: "200000"
        voting_period: "20s"
        expedited_voting_period: "10s"

