[package]
name = "wormhole-cosmwasm"
version.workspace = true
edition = "2021"
description = "Wormhole contract"

[lib]
name = "cw_wormhole"
crate-type = ["cdylib", "rlib"]

[features]
library = []
# enabled, only shutdown functionality is enabled (basically governance).
full = []
default = ["full"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
generic-array = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true, default-features = false, features = ["ecdsa"] }
sha3 = { workspace = true, default-features = false }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true }
