version: "3"

services:
  fusiondnode0:
    container_name: fusiondnode0
    image: "fusiond/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-fusiond.log}
    volumes:
      - ./localnet-setup/node0/fusiond:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  fusiondnode1:
    container_name: fusiondnode1
    image: "fusiond/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-fusiond.log}
    volumes:
      - ./localnet-setup/node1/fusiond:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  fusiondnode2:
    container_name: fusiondnode2
    image: "fusiond/node"
    environment:
      - ID=2
      - LOG=${LOG:-fusiond.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/fusiond:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  fusiondnode3:
    container_name: fusiondnode3
    image: "fusiond/node"
    environment:
      - ID=3
      - LOG=${LOG:-fusiond.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/fusiond:/ethermint:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
