[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "programs/gmp",
    "programs/gmp_with_token",
]

[programs.localnet]
gmp = "DMmiXQDrEwgmt8qHLoqekCRByqJdPn2mYFnfd56FWFE2"
gmp_with_token = "6HmAhnGJeLjasPmptLsScKv7j2Sq7VsKqKaMyUW7bweK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
