---
name: Build and Push Docker

on:
  release:
    types:
      - published
  push:

env:
  AWS_REGION: eu-west-1
  EKS_CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: |
       startsWith(github.ref_name, 'faucet@') ||
       startsWith(github.ref_name, 'wardend@') ||
       startsWith(github.ref_name, 'spaceward@') ||
       startsWith(github.ref_name, 'wardenkms@')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Set tags
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(git show -s --format=%ci ${{ env.COMMIT_SHA }})" >> $GITHUB_ENV
          echo "TAG=$(echo ${GITHUB_REF_NAME} | cut -d'@' -f2)" >> $GITHUB_ENV
          echo "REF=$(echo ${GITHUB_REF_NAME} | cut -d'@' -f1)" >> $GITHUB_ENV
          echo "ECR_REPO=${{ vars.ECR_REGISTRY }}.dkr.ecr.eu-west-1.amazonaws.com/wardenprotocol/production" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        id: image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: ${{ env.REF }}
          build-args: |
             SERVICE=${{ env.REF }}
             GIT_SHA=${{ env.COMMIT_SHA }}
             BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          tags: |
            ${{ env.ECR_REPO }}/${{ env.REF }}:${{ env.SHORT_SHA }}
            ${{ env.ECR_REPO }}/${{ env.REF }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: 'Clone Helm repository'
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.HELM_REPOSITORY }}
          ref: 'main'
          token: ${{ secrets.PAT }}
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      - name: Deploy to EKS
        run: |
          helm upgrade \
           -i ${{ env.REF }} \
           -n devnet \
           --set fullnameOverride=${{ env.REF }} \
           --set image.repository=${{ env.ECR_REPO }}  \
           --set image.name=${{ env.REF }} \
           --set image.tag=${{ env.SHORT_SHA }} \
           ./charts/${{ env.REF }}/
