---
name: docs

on:
  push:
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies (docs)
        run: npm install
        working-directory: "docs/"

      - name: Lint (docs)
        run: npm run lint
        working-directory: "docs/"

      - name: Build (docs)
        run: npm run build
        working-directory: "docs/"

