---
name: semantic_release

on:
  push:
    tags:
      - 'faucet@release-*'
      - 'wardend@release-*'
      - 'web@release-*'
      - 'wardenkms@release-*'
  workflow_run:
    workflows:
      - push
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    if: |
      ${{ 
        github.event_name == 'push' && (
          startsWith(github.ref, 'refs/tags/faucet@release-') ||
          startsWith(github.ref, 'refs/tags/wardend@release-') ||
          startsWith(github.ref, 'refs/tags/web@release-') ||
          startsWith(github.ref, 'refs/tags/wardenkms@release-')
        ) || 
        github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' 
      }}
    steps:
      - name: Echo stuff
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_AUTHOR_EMAIL: 'semanticrelease@wardenprotocol.org'
          GIT_COMMITTER_EMAIL: 'semanticrelease@wardenprotocol.org'
          GIT_AUTHOR_NAME: '@semanticrelease'
          GIT_COMMITTER_NAME: '@semanticrelease'
        run: npx -p @qiwi/semrel-toolkit multi-semrel
